// TODO stop being lazy and finish the types
// not gonna guarantee the validity of any of these types...

export interface Netscape {
  hack(host: string): Promise<number>;
  grow(host: string): Promise<number>;
  weaken(host: string): Promise<number>;
  hackAnalyzeThreads(host: string, amount: number): number;
  hackAnalyzePercent(host: string): number;
  hackChance(host: string): number;
  growthAnalyze(host: string): number;
  sleep(n: number): void;
  print(x: any): void;
  tprint(x: any): void;
  clearLog(): void;
  disableLog(fn: string): void;
  enableLog(fn: string): void;
  isLogEnabled(fn: string): void;
  getScriptLogs(fn: string, host: string, ...args: any[]): void;
  scan(host: string, hostnames: boolean): string[];
  nuke(host: string): void;
  brutessh(host: string): void;
  ftpcrack(host: string): void;
  relaysmtp(host: string): void;
  httpworm(host: string): void;
  sqlinject(host: string): void;
  run(script: string, threads: number, ...args: any[]): void;
  exec(script: string, host: string, threads: number, ...args: any[]): void;
  spawn(script: string, threads: number, ...args: any[]): void;
  kill(script: string, host: string, ...args: any[]): void;
  killall(host: string): void;
  exit(): void;
  scp(files: string[], source: string, destination: string): void;
  ls(host: string, grep: string): string[];
  ps(host?: string);
  hasRootAccess(host: string): boolean;
  getHostname(): string;
  getHackingLevel(): number;
  getHackingMultipliers();
  getHacknetMultipliers();
  getServerMoneyAvailable(host: string): number;
  getServerMaxMoney(host: string): number;
  getServerGrowth(host: string): number;
  getServerSecurityLevel(host: string): number;
  getServerBaseSecurityLevel(host: string): number;
  getServerMinSecurityLevel(host: string): number;
  getServerRequiredHackingLevel(host: string): number;
  getServerNumPortsRequired(host: string): number;
  getServerRam(host: string): number;
  serverExists(host: string): boolean;
  fileExists();
  isRunning();
  getNextHacknetNodeCost();
  purchaseHacknetNode();
  getPurchasedServerCost();
  purchaseServer();
  deleteServer();
  getPurchasedServers();
  getPurchasedServerLimit();
  getPurchasedServerMaxRam();
  write();
  tryWrite();
  read();
  peek();
  clear();
  getPortHandle();
  rm();
  scriptRunning();
  scriptKill();
  getScriptName();
  getScriptRam();
  getHackTime();
  getGrowTime();
  getWeakenTime();
  getScriptIncome();
  getScriptExpGain();
  getTimeSinceLastAug();
  sprintf();
  vsprintf();
  prompt();
  wget();
  getFavorToDonate();

}
